######################################################################
# Automatically generated by qmake (2.01a) seg abr 15 11:33:26 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MenuPage.h SubPage.h
SOURCES += main.cpp MainWindow.cpp MenuPage.cpp SubPage.cpp
